options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/assessment-shabadh/spring-petclinic:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/assessment-shabadh/spring-petclinic:latest'
      - '.'  # Use current directory as build context

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/assessment-shabadh/spring-petclinic'

images:
  - 'gcr.io/assessment-shabadh/spring-petclinic:$COMMIT_SHA'
  - 'gcr.io/assessment-shabadh/spring-petclinic:latest'
