steps: 
  - name: 'gcr.io/cloud-builders/gcloud'
    id: auth-cluster1
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME_1}'
      - '--region=${_REGION_EU}'
      - '--project=${_PROJECT_ID}'
    waitFor: ['-'] # Start immediately

  # Step 1: Rollback deployment in the EU cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    id: rollback-cluster1
    args:
      - 'set'
      - 'image'
      - 'deployment/${_DEPLOYMENT_NAME}'
      - '${_DEPLOYMENT_NAME}=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_VERSION}'
      - '--record'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION_EU}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME_1}'
    waitFor: ['auth-cluster1'] # Start immediately

  # Step 2: Verify rollback status in the EU cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    id: verify-rollback-cluster1
    args:
      - 'rollout'
      - 'status'
      - 'deployment/${_DEPLOYMENT_NAME}'
      - '--timeout=120s' # Wait up to 60 seconds for rollback to stabilize
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION_EU}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME_1}'
    waitFor: ['rollback-cluster1'] # Run after rollback in cluster 1
  
  # Step 3: Authenticate with UK cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    id: auth-cluster2
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME_2}'
      - '--region=${_REGION_UK}'
      - '--project=${_PROJECT_ID}'
    waitFor: ['verify-rollback-cluster1'] # Run after verifying cluster 1

  # Step 4: Rollback deployment in the UK cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    id: rollback-cluster2
    args:
      - 'set'
      - 'image'
      - 'deployment/${_DEPLOYMENT_NAME}'
      - '${_DEPLOYMENT_NAME}=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_VERSION}'
      - '--record'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION_UK}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME_2}'
    waitFor: ['auth-cluster2'] # Run after verifying cluster 1 rollback

  # Step 5: Verify rollback status in the UK cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    id: verify-rollback-cluster2
    args:
      - 'rollout'
      - 'status'
      - 'deployment/${_DEPLOYMENT_NAME}'
      - '--timeout=120s' # Wait up to 60 seconds for rollback to stabilize
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION_UK}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME_2}'
    waitFor: ['rollback-cluster2'] # Run after rollback in cluster 2

substitutions:
  _REGION_EU: 'europe-west4' # Region of the first GKE cluster
  _CLUSTER_NAME_1: 'petclinic-dev-eu' # Name of the first GKE cluster
  _REGION_UK: 'europe-west2' # Region of the second GKE cluster
  _CLUSTER_NAME_2: 'petclinic-dev-uk' # Name of the second GKE cluster
  _DEPLOYMENT_NAME: 'petclinic' # Name of the deployment in both clusters
  _PROJECT_ID: 'assessment-shabadh'
  _IMAGE_NAME: 'petclinic'
  _VERSION: 'v1-20250610165000'

timeout: 300s # Total pipeline timeout
options:
  logging: CLOUD_LOGGING_ONLY