apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic-dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      serviceAccountName: petclinic-sa
      containers:
        - name: petclinic
          image: gcr.io/assessment-shabadh/petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://127.0.0.1:3306/petclinic?useSSL=false"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: SPRING_PROFILES_ACTIVE
              value: "mysql"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false

        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          command:
            - "/cloud_sql_proxy"
            - "-instances=assessment-shabadh:europe-west4:petclinic-db-ha=tcp:3306"
            - "iam-auth-only"
          securityContext:
            runAsNonRoot: true